## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        ddl-auto: update

  database:
    driverClassName: org.hsqldb.jdbcDriver

  datasource:
    url: jdbc:hsqldb:mem:spring
    username: sa
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
